baseURL = "https://www.artfoxes.de"
languageCode = "en-us"
paginate = "6"
summaryLength = "1"
theme = "parsa-hugo"
title = "Artfoxes"
[[menu.main]]
URL = "gallery"
name = "Gallery"
weight = "4"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "Munich  // Bavarian Forest"
author = "Artfoxes"
author_image = "images/IMG_4612.jpg"
bio = "We are two art fanatics from Lower Bavaria"
contact_form_action = "https://formspree.io/mrgajvzy"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "Two creative hearts from Bavaria"
email = "inquiries-artfoxes@web.de"
google_analitycs_id = "UA-163506805-2"
home = "Home"
layout = "2"
logo = "images/logoartfox.png"
mobile = ""
preloader = true
search = true
[params.instafeed]
access_token = "IGQVJYTkZA1MFJ1R1FSUmMza2pmSU1aTTFRWFQtb2F1VnI4VTdTckptSG10X0NMdUt3TWFrRGRRT1VqRHRsZAFlFLU5IeXlfdzZADWjd3c1N6TWw3cmpscVhRR3JwdG81eldTSnBsUzhSU0lobXdMWTEzNAZDZD"
enable = true
user_id = ""
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "https://www.instagram.com/artfo.xes/?hl=de"
icon = "ti-instagram"
